### ISSUE TITLE
Secret file which generates encrypted pw db does not get deleted.

### ISSUE THREAD

**Issue by do3cc** [debops/ansible-postfix#22]
There is still my password visible:
/etc/postfix/private_hash_tables

**Comment by drybjed** [comment]
Deletion of the source file is a good idea, however there are some issues to fix first.

How to stop Ansible from endlessly regenerating that file? A marker file possibly, used with `creates=`. And it cannot be a `.db` file since otherwise that one won't be created.

If we do a marker file, that means that to add new passwords, user would need to remove that file. I suppose that's OK if we mention it in the defaults file where people are likely to look anyway.

**Comment by do3cc** [comment]
maybe one step to empty the file afterwards

**Comment by do3cc** [comment]
create a custom command
