### ISSUE TITLE
Add support for Cyrus SASL authentication

### ISSUE THREAD

**Issue by ganto** [debops/ansible-postfix#36]
I'm trying to rebuild my postfix setup with debops. To make this work correctly, I need Cyrus SASL support for user authentication. I hacked together something (f4c27a0) as an addition to the postfix role which works for my setup.

Are you interested in this? If so, is this the correct place to add this, or should this go to separate role. So far I hardcoded authentication support via PAM. However other people might have more complicated authenticaton requirements via MySQL or LDAP.

What is best practise in Ansible to add file "templates" which are completely static, such as in my case e.g. `/etc/postfix/sasl/smtpd.conf`. Is this correct to do via jinja2 template?

Any comment is welcome :-)

**Comment by drybjed** [comment]
This is awesome! :-) So, to be sure - with this you can authenticate correctly to local system user accounts on `submission` port? Assuming that `network` and `submission` are enabled in Postfix capabilities of course. That probably would conflict with Dovecot, so good thinking about including a variable which can be used to switch between them in the future.

I would like to add `dovecot` at some point for IMAP4/POP3 as a separate role. For more complex setups (for example Postfixadmin or `vmm`) I would rather see a separate role that uses `debops.postfix` and `debops.dovecot` as role dependencies and passes configuration to them via dependency variables.

Sure, templating static files is fine, in case that you want to add some variables in the future. Also, if it's just only 1 file, creating separate `files/` directory seems like a waste.

**Comment by ganto** [comment]
Yes, with this i can do a AUTH LOGIN on the submission port, which then authenticates against a system account on the SMTP server. Maybe I should also allow a `postfix_smtpd_sasl_type = map` which would authenticate against a password map file as you do it for the `sender_dependent` capability. However, I never tried this setup myself...

Ya, a `dovecot` role would be awsome. I'd also like to have `amavisd` integration which I might have a look at later.

**Comment by drybjed** [comment]
Anti-spam is hard because you want to setup a chain of filters. `dspam`, `bld`, `amavis`, `spamassassin` all would be nice, sure.

Postfix role needs some love, I think. Firstly, time to switch to 2.11+ from Wheezy Backports in preparation to Jessie. When this happens, we will get `smtpd_relay_restrictions` which will make access control easier to manage.

As you probably noticed, we are ramping up on LDAP so I would look for adding support for different databases as well. I'm not sure if it should be directly in `debops.postfix` yet (it is massive, and system accounts only setup is viable on its own), it would probably work better as an additional role which sets up files in `/etc/postfix/<somedir>/` and uses Postfix as a dependency, configuring the access to the `.cf` files via dependency variables.

Also, how do you like this mechanism? Have you seen `debops.smstools` or `debops.mailman`?

**Comment by drybjed** [comment]
@ganto Also, do a pull request, let's see how it goes. :-) And swing by IRC channel if you like.
