### ISSUE TITLE
secret not generating password file

### ISSUE THREAD

**Issue by leviwheatcroft** [debops/ansible-postfix#48]
The docs [here](http://docs.debops.org/en/latest/ansible/roles/ansible-postfix/docs/defaults-configuration.html#postfix-smtp-sasl-password-map) say if I run the postfix playbook without the password file secret will generate it automatically. 

That doesn't seem to be happening. In addition, if I create the password file myself it doesn't seem to be copied across to the remote host, but I'm not really sure how to confirm given that the .db file on the remote host is binary?

the docs, and the playbook, suggest that so long as I have 'client' capability specified, and set postfix_smtp_sasl_password_map then I should be ready to rock.

Sorry I'm a bit lost and not sure how to troubleshoot further.

my config looks like this:
```
# Specify a mail server to send all mail through (it needs to accept the
# incoming messages from your host)
postfix_relayhost: 'smtp.mandrillapp.com'

# Set a default admin e-mail address where all messages to root account will
# be forwarded
postfix_default_local_alias_recipients: [ 'my@email.com' ]

postfix: [ 'client', 'mx', 'network' ]

postfix_mailname: '{{ ansible_fqdn }}'
postfix_mydomain: '{{ ansible_domain }}'

postfix_smtp_sasl_password_map: 
  'smtp.mandrillapp.com': 'my@email.com'


postfix_allow_submission: [192.168.0.0/24]
postfix_allow_smtp: [192.168.0.0/24]
```

**Comment by drybjed** [comment]
This issue is related to https://github.com/debops/ansible-postfix/issues/41

Basically, to keep the passwords private and hashed, `debops.postfix` generates the `.db` map and removes the source file replacing it with `/etc/postfix/private_hash_tables/smtp_sasl_password_map.lock` file. This file is a placeholder to tell `debops.postfix` role to not regenerate the hashed map.

If you remove this file (`.lock`), and re-run `debops.postfix`, your passwords will be created correctly. Of course to replace the random passwords with your own you will need to remove it again.

I suppose right now it's not very roboust system, I'm looking into a replacement.

**Comment by leviwheatcroft** [comment]
That solved it. Thankyou.
