### ISSUE TITLE
Forward all mail to admin user in SMTP client mode

### ISSUE THREAD

**Issue by sread** [debops/ansible-postfix#61]
I'm using `postfix: [ 'client' ]` and I think I've set the sasl password map / passwords properly. My understanding is that `postfix_default_local_alias_recipients` won't work in this case, so what should I use? #11 seems relevant but I don't quite understand how it's meant to be implemented after the described change.

Variables I've used (where ansible_domain is example.com, and there is an existing non-debops SMTP server at mail.example.com). Also debops_admin_user@example.com exists.

```
postfix_relayhost: 'mail.example.com'
postfix: [ 'client' ]
postfix_smtp_sasl_password_map:
  'mail.example.com': 'username'
```

**Comment by drybjed** [comment]
The clue's in the name :-) postfix_default_**local**_alias_recipients. Basically, forwarding mail through `/etc/aliases` works only when the `local` Postfix capability is enabled (ie. local mail delivery), otherwise everything is explicitly sent out either directly, or to relayhost. So, try enabling the `local` capability, then it should work as expected.

**Comment by drybjed** [comment]
The support for local mail aliases has been moved to the [`debops.etc_aliases`](https://github.com/debops/ansible-etc_aliases) Ansible roles. I'm closing this issue here.
