### ISSUE TITLE
submission options

### ISSUE THREAD

**Issue by bleuchtang** [debops/ansible-postfix#88]
Here https://github.com/debops/ansible-postfix/blob/master/templates/etc/postfix/master.cf/submission.j2#L13 we have no_address_mappings option. I think this option is not necessary and moreover it skip virtual alias mapping witch is really annoying.

Maybe we can provide a template with variables ?

**Comment by drybjed** [comment]
Agreed. The `debops.postfix` role has been written a long time ago and hasn't seen much updates since. The Postfix configuration should be much more flexible to begin with, moving much of the options to defaults would allow for more flexibility.

NB, the role hasn't been written to support virtual mailboxes, I planned to add that in the future. But I guess that other things took priority in the meantime. The mail stack hasn't been upgraded since the switch from Postfix as the default SMTP server to nullmailer... But updating the `debops.postfix` role should probably take priority before adding more roles for mail management.

**Comment by bleuchtang** [comment]
Ok. What did you propose ? remove this option or transform it in variable ?

**Comment by drybjed** [comment]
If you want to work on this, the `master.cf` configuration should be defined as YAML dictionaries with a default set of services. The service state should be controllable via conditions. You can check out changes to `debops.ferm` and `debops.ifupdown` (the PRs, mostly) to see where I'm going with this.

This way the role can provide some good defaults, and if needed users should be able to override them to suit their own needs.

**Comment by bleuchtang** [comment]
Think that a big part of the job is done here :https://github.com/debops/ansible-postfix/blob/master/templates/etc/ansible/facts.d/postfix.fact.j2#L179
Maybe this code shoud be in a macro and every template should call this macro.

**Comment by drybjed** [comment]
After the redesign of the `debops.postfix` role the management of the `submission` service has been moved to the [`debops.postconf`](https://github.com/debops/ansible-postconf) role. I'm closing this issue as resolved.
